# Generated by Django 4.1.5 on 2023-01-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='child',
        ),
        migrations.AddField(
            model_name='item',
            name='children',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu_app.item'),
        ),
    ]
