# Generated by Django 4.1.5 on 2023-01-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_item_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='children',
        ),
    ]
