# Generated by Django 4.1.5 on 2023-01-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_item_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.item'),
        ),
    ]
