# Generated by Django 4.1.5 on 2023-01-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_rename_children_item_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
