# Generated by Django 4.1.5 on 2023-01-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0010_rename_active_item_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='selected',
        ),
    ]
